const gameData = [
  {
    id: 1,
    imgsrc: "https://www.shutterstock.com/shutterstock/photos/2397428743/display_1500/stock-photo-introducing-the-game-that-has-been-awaited-for-years-grand-theft-auto-vi-2397428743.jpg",
    heading: "Grand Theft Auto VI",
    description: "Introducing the game that has been awaited for years, Grand Theft Auto VI! Click show more for details.",
    details: "Grand Theft Auto VI is an upcoming open-world action-adventure game developed by Rockstar Games. Set in Vice City, it features a gripping storyline, immersive gameplay, and next-gen graphics.Grand Theft Auto VI is the highly anticipated entry in Rockstar Games' iconic franchise. Set in the sprawling, dynamic world of Vice City, the game promises an immersive experience with a rich narrative, detailed environments, and complex characters. Players can explore a vast open world filled with opportunities for crime, adventure, and mayhem. The game's next-gen graphics and enhanced mechanics offer a seamless and realistic gaming experience. With a focus on storytelling, Grand Theft Auto VI delves into the gritty underworld of Vice City, introducing new protagonists and storylines. ",
    releaseDate: "2025-11-17",
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    genres: ["All","Action", "Adventure", "Strategy"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 970 or equivalent",
    platforms: ["PC", "PS5", "Xbox Series X"],
    youtubeGameplay: "https://www.youtube.com/embed/QdBZY2fkU-0?si=UiPhkQcOQ0q_oXWI",
  },
  {
    id: 2,
    imgsrc: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_1.5/c_scale,w_900/ncom/software/switch/70010000047794/40f9e2f6d344d2607d4be72c6c4ebd3c18717ff87a56d6bbc303c42e58dd570d",
    heading: "FIFA 23",
    description: "FIFA 23 is a football simulation game that offers realistic gameplay, enhanced graphics, and new features like HyperMotion2 technology.",
    details: "FIFA 23 introduces women's club football, HyperMotion2 gameplay technology, and cross-play. Enjoy updated rosters, improved animations, and an immersive football experience.FIFA 23, developed by EA Sports, is the latest installment in the long-running football simulation series. The game introduces HyperMotion2 technology, enhancing the realism and fluidity of player movements and animations. FIFA 23 features updated rosters, reflecting the latest transfers and player ratings, along with improved graphics and stadium atmospheres. The game includes women's club football, expanding the diversity of teams and competitions available. With cross-play functionality, players can compete with friends across different platforms. FIFA 23's Career Mode allows players to manage a team, make strategic decisions, and guide their club to glory. ",
    releaseDate: "2022-09-30",
    developer: "EA Sports",
    publisher: "EA Sports",
    genres: ["All","Sports", "Simulation"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 1050 or equivalent",
    platforms: ["PC", "PS5", "Xbox Series X"],
    youtubeGameplay: "https://www.youtube.com/embed/Ye1Go-Ke1r4?si=2U3-Pgt09yFiLzc8",
  },
  {
    id: 3,
    imgsrc: "https://i.ytimg.com/vi/EAPldVCRo-g/maxresdefault.jpg",
    heading: "The Legend of Zelda: Skyward Sword",
    description: "Join Link on an epic adventure through the skies and beyond in this remastered version of The Legend of Zelda: Skyward Sword.",
    details: "Experience The Legend of Zelda: Skyward Sword HD with enhanced visuals, refined controls, and a rich storyline that delves into the origins of the Master Sword. The Legend of Zelda: Skyward Sword HD is a remastered version of the beloved classic, offering enhanced visuals and refined controls. Set in the fantastical world of Hyrule, the game follows the adventures of Link as he embarks on a quest to rescue Princess Zelda and uncover the origins of the Master Sword. Players can explore a vast sky world, filled with floating islands and dungeons, using the unique motion controls of the Nintendo Switch. The game's story is rich with lore, delving into the mythology of the Zelda series. Combat is intuitive, with players using the Joy-Con controllers to wield the sword and shield.",
    releaseDate: "2023-03-03",
    developer: "Nintendo",
    publisher: "Nintendo",
    genres: ["All","Action", "Adventure", "RPG"],
    systemRequirements: "Exclusive on Nintendo Switch",
    platforms: ["Nintendo Switch"],
    youtubeGameplay: "https://www.youtube.com/embed/EAPldVCRo-g?si=T_YfrKtjUT0FKjvp",
  },
  {
    id: 4,
    imgsrc: "https://i.ytimg.com/vi/D1H4o4FW-wA/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCeEG47i3U5Bou3VKKhvH0bC4TzjQ",
    heading: "Elden Ring",
    description: "Elden Ring, a collaboration between FromSoftware and George R.R. Martin, takes you on a dark fantasy adventure.",
    details: "Elden Ring features a vast open world, deep lore, and challenging combat. Explore the mysterious Lands Between and forge your own destiny. Elden Ring, developed by FromSoftware in collaboration with George R.R. Martin, is a dark fantasy action RPG set in the vast and mysterious Lands Between. Players take on the role of a Tarnished, a being seeking to reclaim the power of the Elden Ring and become the Elden Lord. The game features a sprawling open world, filled with challenging enemies, intricate dungeons, and hidden secrets. Elden Ring's combat system combines elements of FromSoftware's previous titles, with a focus on precise timing and strategy. Players can customize their character's abilities, weapons, and equipment to suit their playstyle.",
    releaseDate: "2022-02-25",
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    genres: ["All","Action", "RPG", "Adventure"],
    systemRequirements: "PC: Intel i7, 16GB RAM, GTX 1070 or equivalent",
    platforms: ["PC", "PS5", "Xbox Series X"],
    youtubeGameplay: "https://www.youtube.com/embed/E3Huy2cdih0?si=IRKVeZLuu6-Nr1-g",
  },
  {
    id: 5,
    imgsrc: "https://www.cyberpunk.net/build/images/social-thumbnail-en-ddcf4d23.jpg",
    heading: "Cyberpunk 2077",
    description: "Immerse yourself in the neon-lit streets of Night City in Cyberpunk 2077. Experience a gripping story and dynamic characters.",
    details: "Cyberpunk 2077 is an open-world RPG set in a futuristic metropolis, where choices shape your story in a city full of intrigue and high-tech enhancements. The game's narrative is driven by player choices, with branching storylines and multiple endings. Night City is a vibrant and immersive world, filled with diverse characters, bustling streets, and high-tech gadgets. The game's combat system combines gunplay, melee attacks, and hacking abilities, allowing players to approach challenges in various ways. Cyberpunk 2077 also features a deep customization system, enabling players to modify V's appearance, skills, and augmentations. The game's rich lore and detailed environments create a captivating experience, while its next-gen graphics and dynamic weather effects enhance immersion. ",
    releaseDate: "2020-12-10",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genres: ["All","Racing", "Strategy", "Sci-Fi"],
    systemRequirements: "PC: Intel i7, 16GB RAM, GTX 1080 or equivalent",
    platforms: ["PC", "PS5", "Xbox Series X"],
    youtubeGameplay: "https://www.youtube.com/embed/8X2kIfS6fb8?si=O-bCequMmTvNT0lr",
  },
  {
    id: 6,
    imgsrc: "https://cdn1.epicgames.com/offer/cbd5b3d310a54b12bf3fe8c41994174f/EGS_VALORANT_RiotGames_S1_2560x1440-1dade6e50659c8e05805cb150b349e56",
    heading: "Valorant",
    description: "Valorant is a competitive tactical shooter from Riot Games, blending precise gunplay with unique agent abilities.",
    details: "Valorant is a team-based shooter where strategy and skill combine. Choose an agent, master your abilities, and compete in fast-paced tactical battles. Each agent in Valorant has distinct abilities that can be used to gain an advantage in combat, from deploying barriers to healing teammates. The game's mechanics are designed to reward skill and precision, with a focus on headshots and recoil control. Valorant's maps are carefully crafted to offer various strategic opportunities, including tight corridors, open spaces, and verticality. The game's ranked mode provides a competitive environment for players to test their skills and climb the leaderboards. Valorant also features a vibrant esports scene, with regular tournaments and events. Riot Games continues to support Valorant with frequent updates, introducing new agents, maps, and gameplay changes to keep the experience fresh and engaging.",
    releaseDate: "2020-06-02",
    developer: "Riot Games",
    publisher: "Riot Games",
    genres: ["All","FPS", "Action", "Strategy",],
    systemRequirements: "PC: Intel i3, 4GB RAM, integrated graphics",
    platforms: ["PC"],
    youtubeGameplay: "https://www.youtube.com/embed/e_E9W2vsRbQ?si=ksd-hMlosWWHcU9S",
  },
  {
    id: 7,
    imgsrc: "https://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2015/5/13/1431520130189/8bfad8ae-5a24-4617-988e-ccafee83324f-1020x612.jpeg?width=700&quality=85&auto=format&fit=max&s=8a7d3e78ea1329d9442f2b175bc7eb14",
    heading: "The Witcher 3: Wild Hunt",
    description: "An epic RPG with a rich story and immersive world.",
    details: "The Witcher 3: Wild Hunt is an action RPG set in a fantasy world. Players take on the role of Geralt of Rivia, a monster hunter searching for his adopted daughter. The game features a vast open world, engaging combat, and deep storytelling. The open world of The Witcher 3 is filled with diverse regions, from bustling cities to dense forests, each with its own unique quests and challenges. Combat is dynamic and requires strategic use of Geralt's abilities, including swordplay, magic, and alchemy. The game's deep lore and detailed environments create a captivating experience, while its stunning visuals and atmospheric soundtrack enhance immersion. The Witcher 3 also features two major expansions, Hearts of Stone and Blood and Wine, which introduce new storylines, characters, and regions to explore. ",
    releaseDate: "2015-05-19",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genres: ["All","RPG", "Strategy", "Action"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 770 or equivalent",
    platforms: ["PC", "PS4", "Xbox One", "Nintendo Switch"],
    youtubeGameplay: "https://www.youtube.com/embed/c0i88t0Kacs?si=1Z_8bxMHWbN-HJPJ",
  },
  {
    id: 8,
    imgsrc: "https://store-images.s-microsoft.com/image/apps.60323.13950084616086229.56d90257-df96-4000-bf85-a64704b3b019.d4ae0460-e24a-41ce-9e09-a92dc478362f?mode=scale&q=90&h=720&w=1280&format=jpg",
    heading: "Minecraft",
    description: "A sandbox game where you can build and explore endlessly.",
    details: "Minecraft is a sandbox game that allows players to explore, build, and create in a blocky, procedurally-generated world. Players can gather resources, craft items, and build structures while facing challenges such as monsters and environmental hazards. The game features various modes, including Survival, Creative, and Adventure, each offering a different experience. In Survival mode, players must gather resources, craft items, and fend off hostile creatures to survive. Creative mode allows players to build freely without constraints, with unlimited resources at their disposal. Adventure mode offers custom maps and challenges created by the community. Minecraft's blocky art style and simple mechanics make it accessible to players of all ages. The game also supports multiplayer, allowing players to collaborate or compete with others online. Minecraft's vibrant community continues to create new content, from mods and texture packs to custom maps and mini-games. ",
    releaseDate: "2011-11-18",
    developer: "Mojang Studios",
    publisher: "Mojang Studios",
    genres: ["All","Puzzle", "Survival", "Adventure"],
    systemRequirements: "PC: Intel i3, 4GB RAM, integrated graphics",
    platforms: ["PC", "PS4", "Xbox One", "Nintendo Switch", "Mobile"],
    youtubeGameplay: "https://www.youtube.com/embed/MmB9b5njVbA?si=SBTFEs3Oh6repGl2",
  },
  {
    id: 9,
    imgsrc: "https://gaming-cdn.com/images/products/9456/616x353/league-of-legends-pc-game-cover.jpg?v=1662363312",
    heading: "League of Legends",
    description: "A highly competitive multiplayer online battle arena game.",
    details: "League of Legends is a MOBA game where players control a champion with unique abilities and work with their team to destroy the enemy's Nexus. The game requires strategy, teamwork, and quick reflexes.Each match begins with players choosing their champions and selecting items to enhance their abilities. The game's map, Summoner's Rift, features three lanes, a jungle area, and various objectives, such as turrets and inhibitors, that players must control to gain an advantage. League of Legends has a diverse roster of champions, each with their own playstyle and lore. The game's ranked mode provides a competitive environment where players can test their skills and climb the ladder. Riot Games regularly updates the game with balance changes, new champions, and events, keeping the experience fresh and engaging. ",
    releaseDate: "2009-10-27",
    developer: "Riot Games",
    publisher: "Riot Games",
    genres: ["All","MOBA", "Strategy", "Action"],
    systemRequirements: "PC: Intel i3, 4GB RAM, integrated graphics",
    platforms: ["PC"],
    youtubeGameplay: "https://www.youtube.com/embed/vzHrjOMfHPY?si=CDwzvTaELKTh_YKW",
  },
  {
    id: 10,
    imgsrc: "https://miro.medium.com/v2/resize:fit:800/0*tEg_A9lgZRP4_LkI.jpg",
    heading: "Counter-Strike: Global Offensive",
    description: "A classic first-person shooter with intense gameplay.",
    details: "Counter-Strike: Global Offensive (CS: GO) is a first-person shooter where players join either the terrorist or counter-terrorist team. The game features various modes, including competitive matchmaking, where strategy and precision are key. The game's mechanics reward precise aiming, map knowledge, and teamwork. Each round begins with players purchasing weapons and equipment using money earned from previous rounds. CS: GO's maps are meticulously designed to offer various strategic opportunities, from tight corridors to open spaces. The game's competitive matchmaking provides a ranked environment where players can test their skills and climb the ladder. CS: GO also features a vibrant community and esports scene, with regular tournaments and events. Valve continues to support the game with updates, introducing new maps, weapons, and gameplay changes. The game's legacy and enduring popularity make it a staple in the first-person shooter genre.",
    releaseDate: "2012-08-21",
    developer: "Valve",
    publisher: "Valve",
    genres: ["All","FPS", "Action", "Strategy"],
    systemRequirements: "PC: Intel i3, 4GB RAM, GTX 750 or equivalent",
    platforms: ["PC"],
    youtubeGameplay: "https://www.youtube.com/embed/edYCtaNueQY?si=Lxxbk7D7tRVaef4w",
  },
  {
    id: 11,
    imgsrc: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/570/header.jpg?t=1739210483",
    heading: "Dota 2",
    description: "A popular multiplayer online battle arena (MOBA) game with deep strategy.",
    details: "Dota 2 is a competitive MOBA developed by Valve, featuring a vast roster of heroes, strategic gameplay, and intense team battles. Players pick a hero and work with their team to destroy the enemy's Ancient while defending their own. The game has a steep learning curve but offers immense rewards for skillful play. With regular updates, an active esports scene, and millions of players worldwide, Dota 2 remains one of the most competitive online games. The game's competitive scene is thriving, with major tournaments like The International drawing massive audiences and offering substantial prize pools. With regular updates, a dedicated community, and a rich esports ecosystem, Dota 2 continues to be a cornerstone of the MOBA genre.",
    releaseDate: "2013-07-09",
    developer: "Valve",
    publisher: "Valve",
    genres: ["All","Action", "Strategy", "Causal"],
    systemRequirements: "PC: Intel i3, 4GB RAM, DirectX 9 compatible GPU",
    platforms: ["PC"],
    youtubeGameplay: "https://www.youtube.com/embed/-cSFPIwMEq4?si=8XtQt4JW-Ho7EYJc",
  },
  {
    id: 12,
    imgsrc: "https://i.pinimg.com/736x/b0/cd/bd/b0cdbda5558cce6196f046b11f945c3b.jpg",
    heading: "PUBG: Battlegrounds",
    description: "A battle royale game where players fight to be the last one standing.",
    details: "PUBG (PlayerUnknown's Battlegrounds) is a battle royale shooter where 100 players parachute onto an island and fight to survive. Players scavenge for weapons, armor, and supplies while staying within a shrinking safe zone. The game emphasizes tactical play, gunfights, and survival instincts. PUBG has been a pioneer in the battle royale genre, inspiring countless other games and maintaining a dedicated player base. With a variety of maps, game modes, and frequent updates, PUBG continues to captivate millions of players worldwide and has significantly influenced the popularity of the battle royale genre.",
    releaseDate: "2017-12-20",
    developer: "PUBG Studios",
    publisher: "Krafton",
    genres: ["All","Battle Royale", "Shooter", "Survival"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 960 or equivalent",
    platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X", "Mobile"],
    youtubeGameplay: "https://www.youtube.com/embed/u1oqfdh4xBY?si=0yPLoFKXXQjbU1si",
  },
  {
    id: 13,
    imgsrc: "https://assets.xboxservices.com/assets/a0/02/a0029671-98a2-4955-a9e7-ef32cd0eb544.jpg?n=CoD-MW-II_GLP-Page-Hero-Poster-1084_1920x1080.jpg",
    heading: "Call of Duty: Modern Warfare II",
    description: "A first-person shooter with realistic combat and engaging multiplayer.",
    details: "Call of Duty: Modern Warfare II is a high-paced first-person shooter that blends an intense campaign with competitive multiplayer modes. The game features realistic gunplay, cinematic storytelling, and a variety of maps and weapons. With Warzone integration, it also includes battle royale and co-op missions, making it one of the most popular FPS games.The game features a variety of modes, including a thrilling campaign where players engage in high-stakes missions, a competitive multiplayer mode with new and classic game types, and a cooperative Special Ops mode that requires tactical teamwork. ",
    releaseDate: "2022-10-28",
    developer: "Infinity Ward",
    publisher: "Activision",
    genres: ["All","FPS", "Action", "Shooter"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 970 or equivalent",
    platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X"],
    youtubeGameplay: "https://www.youtube.com/embed/ztjfwecrY8E?si=ThM_k8anY973-kNG",
  },
  {
    id: 14,
    imgsrc: "https://media.contentapi.ea.com/content/dam/need-for-speed/nfs-heat/common/wallpapers/nsfh-wallpaper-keyart-deluxe-16x9.png",
    heading: "Need for Speed: Heat",
    description: "A high-speed racing game with a thrilling open-world experience.",
    details: "Need for Speed: Heat is an open-world racing game that offers intense street races, police chases, and car customization. Players can race in sanctioned daytime events or take risks in illegal nighttime street races to earn rewards. The game features stunning graphics, a diverse selection of cars, and immersive driving mechanics, making it a favorite among racing enthusiasts. With a diverse roster of cars, extensive customization options, and a gripping storyline, NFS Heat captures the adrenaline-pumping essence of street racing and the allure of the underground racing scene. The game's stunning visuals, dynamic weather, and engaging gameplay make it a standout title in the Need for Speed series.",
    releaseDate: "2019-11-08",
    developer: "Ghost Games",
    publisher: "Electronic Arts",
    genres: ["All","Racing", "Action", "Strategy"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 760 or equivalent",
    platforms: ["PC", "PS4", "Xbox One"],
    youtubeGameplay: "https://www.youtube.com/embed/9ewiJJe_nYI?si=Nj7Nv8VkcoZgD3cZ",
  },
  {
    id: 15,
    imgsrc: "https://www.theland.com.au/images/transform/v1/crop/frm/187038826/c534ed48-33cf-49e6-bc1c-b42ece8c3415.jpg/r0_0_3840_2159_w1200_h678_fmax.jpg",
    heading: "Farming Simulator 2024",
    description: "Experience the ultimate farming simulation with realistic machinery, crops, and livestock!",
    details: "Farming Simulator 2024 offers a deep farming experience with advanced AI, new crop types, and enhanced weather mechanics.",
    releaseDate: "2024-09-15",
    developer: "GIANTS Software",
    publisher: "Focus Entertainment",
    genres: ["All","Simulation"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 960 or equivalent",
    platforms: ["PC", "PS5", "Xbox Series X"],
    youtubeGameplay: "https://www.youtube.com/embed/FS2024Game",
  },
  {
    id: 16,
    imgsrc: "https://cdn.mos.cms.futurecdn.net/3jxR4s6pAEYvbDcD8GsUwZ.jpg",
    heading: "City Builder Simulator 2025",
    description: "Design, build, and manage your own city in this immersive simulation game.",
    details: "City Builder Simulator 2025 allows players to create a thriving metropolis, manage resources, and respond to disasters.",
    releaseDate: "2025-06-10",
    developer: "UrbanSim Studios",
    publisher: "Epic Games",
    genres: ["All","Simulation"],
    systemRequirements: "PC: Intel i7, 16GB RAM, RTX 2060 or equivalent",
    platforms: ["PC", "PS5"],
    youtubeGameplay: "https://www.youtube.com/embed/CityBuildSim2025",
  },

  // 🔹 Puzzle Games (2 More)
  {
    id: 17,
    imgsrc: "https://static.vecteezy.com/system/resources/previews/007/652/221/non_2x/square-maze-labyrinth-game-for-kids-logic-conundrum-four-entrance-and-one-right-way-to-go-flat-illustration-isolated-on-white-background-vector.jpg",
    heading: "Logic Maze Challenge",
    description: "Solve intricate mazes and puzzles that test your logic and strategy skills!",
    details: "Logic Maze Challenge features over 200 levels of brain-teasing puzzles with increasing difficulty.",
    releaseDate: "2024-03-20",
    developer: "MindTwist Games",
    publisher: "PuzzleMasters Inc.",
    genres: ["All","Puzzle"],
    systemRequirements: "PC: Intel i3, 4GB RAM, Integrated Graphics",
    platforms: ["PC", "Mobile", "Switch"],
    youtubeGameplay: "https://www.youtube.com/embed/LogicMazeGame",
  },
  {
    id: 18,
    imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1kdMak4h3GTDeTN1UGhKcOGSVnckE8FqPK9GeHWXaMEY6ljHc2qDXxSdYA-oDaTuAIF8&usqp=CAU",
    heading: "Mystic Runes Quest",
    description: "Match runes, solve mysteries, and uncover ancient secrets in this engaging puzzle adventure.",
    details: "Mystic Runes Quest combines match-3 mechanics with an immersive storyline featuring mystical artifacts.",
    releaseDate: "2025-08-05",
    developer: "RuneCraft Studios",
    publisher: "PuzzleX Games",
    genres: ["All","Puzzle"],
    systemRequirements: "PC: Intel i5, 6GB RAM, GTX 1050 or equivalent",
    platforms: ["PC", "Mobile"],
    youtubeGameplay: "https://www.youtube.com/embed/MysticRunesQuest",
  },

  // 🔹 Educational Games (2 More)
  {
    id: 19,
    imgsrc: "https://img-c.udemycdn.com/course/750x422/1404594_b413_2.jpg",
    heading: "Learn to Code: The Game",
    description: "An interactive coding adventure that teaches programming through fun challenges!",
    details: "This game introduces coding concepts using real-world programming languages in an engaging format.",
    releaseDate: "2024-12-01",
    developer: "EduTech Labs",
    publisher: "CodeAcademy",
    genres: ["All","Educational"],
    systemRequirements: "PC: Intel i3, 4GB RAM, Integrated Graphics",
    platforms: ["PC", "Mobile"],
    youtubeGameplay: "https://www.youtube.com/embed/LearnToCodeGame",
  },
  {
    id: 20,
    imgsrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKIS5opk7d7wok2jq45AGJr8hlarEUBEi0GQ&s",
    heading: "Space Explorer: Science Quest",
    description: "Explore the universe, conduct experiments, and learn about space in this interactive educational game.",
    details: "Space Explorer lets players discover planets, learn physics, and simulate space missions.",
    releaseDate: "2025-05-15",
    developer: "AstroLearn Studios",
    publisher: "NASA EdTech",
    genres: ["All","Educational"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 950 or equivalent",
    platforms: ["PC", "Mobile", "Switch"],
    youtubeGameplay: "https://www.youtube.com/embed/SpaceExplorerGame",
  },
  
  {
    id: 21,
    imgsrc: "https://www.zelda.com/breath-of-the-wild/assets/icons/BOTW-Share_icon.jpg",
    heading: "The Legend of Zelda: Breath of the Wild",
    description: "Step into a new world and explore the majestic Hyrule in this open-world action-adventure.",
    details: "The Legend of Zelda: Breath of the Wild offers a vast open world, a deep storyline, and a unique combination of action, puzzle-solving, and exploration.",
    releaseDate: "2017-03-03",
    developer: "Nintendo",
    publisher: "Nintendo",
    genres: ["All","Adventure","Simulation", "Causal"],
    systemRequirements: "NES Classic Edition: NES, 2MB RAM, 32KB VRAM",
    platforms: ["NES Classic Edition"],
    youtubeGameplay: "https://www.youtube.com/embed/9r9s263v80I",
  },
  {
    id: 22,
    imgsrc: "https://www.rocketleague.com/images/keyart/rl_evergreen.jpg",
    heading: "Rocket League",
    description: "A unique mix of soccer and vehicular mayhem! Drive, jump, and score in Rocket League.",
    details: "Rocket League combines fast-paced car gameplay with soccer mechanics. Compete in online multiplayer or local matches.",
    releaseDate: "2015-07-07",
    developer: "Psyonix",
    publisher: "Psyonix",
    genres: ["All","Sports"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 660 or equivalent",
    platforms: ["PC", "PS4", "Xbox One", "Switch"],
    youtubeGameplay: "https://www.youtube.com/embed/omI392UQWkw",
  },
  {
    id: 23,
    imgsrc: "https://oyster.ignimgs.com/mediawiki/apis.ign.com/fifa-soccer-14/a/a1/FIFA-14-Gameplay.jpg",
    heading: "FIFA 14",
    description: "Experience the beautiful game with FIFA 14, featuring realistic physics and gameplay.",
    details: "FIFA 14 offers advanced ball physics, precision movement, and a deep career mode to build your ultimate team.",
    releaseDate: "2013-09-24",
    developer: "EA Sports",
    publisher: "Electronic Arts",
    genres: ["All","Sports"],
    systemRequirements: "PC: Intel Core 2 Quad, 4GB RAM, GTX 650 or equivalent",
    platforms: ["PC", "PS3", "PS4", "Xbox 360", "Xbox One"],
    youtubeGameplay: "https://www.youtube.com/embed/kFOHszorXrw",
  },
  {
    id: 24,
    imgsrc: "https://store-images.s-microsoft.com/image/apps.58752.13942869738016799.078aba97-2f28-440f-97b6-b852e1af307a.95fdf1a1-efd6-4938-8100-8abae91695d6?q=90&w=480&h=270",
    heading: "Red Dead Redemption 2",
    description: "A gritty Western open-world adventure with a rich storyline and a deep character development.",
    details: "Red Dead Redemption 2 offers a vast open world, a deep storyline, and a unique combination of action, stealth, and survival.",
    releaseDate: "2018-10-26",
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    genres: ["All","Action", "Adventure", "Strategy"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 1060 or equivalent",
    platforms: ["PC", "PS4", "Xbox One"],
    youtubeGameplay: "https://www.youtube.com/embed/V4dDspKQ14s",
  },
  {
    id: 25,
    imgsrc: "https://assets.nintendo.com/image/upload/q_auto/f_auto/ncom/software/switch/70010000001369/3a41386d4b0999365727a21cc5c13853cfc244abca39b689bb79a339601e48c3",
    heading: "The Elder Scrolls V: Skyrim",
    description: "A open-world action RPG with a rich storyline and a deep character development.",
    details: "Skyrim offers a vast open world, a deep storyline, and a unique combination of action, magic, and exploration.",
    releaseDate: "2011-11-11",
    developer: "Bethesda Game Studios",
    publisher: "Bethesda Softworks",
    genres: ["All","Action", "Adventure", "Strategy"],
    systemRequirements: "PC: Intel i5, 4GB RAM, GTX 650 or equivalent",
    platforms: ["PC", "PS4", "Xbox One"],
    youtubeGameplay: "https://www.youtube.com/embed/Q20J31iazJk",
  },
  {
    id: 26,
    imgsrc: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/220240/capsule_616x353.jpg?t=1738250672",
    heading: "Far Cry 3",
    description: "A open-world action adventure with a rich storyline and a deep character development.",
    details: "Far Cry 3 offers a vast open world, a deep storyline, and a unique combination of action, stealth, and exploration.",
    releaseDate: "2012-11-16",
    developer: "Ubisoft",
    publisher: "Ubisoft",
    genres: ["All","Action", "Adventure", "Strategy"],
    systemRequirements: "PC: Intel i5, 4GB RAM, GTX 650 or equivalent",
    platforms: ["PC", "PS3", "PS4", "Xbox 360", "Xbox One"],
    youtubeGameplay: "https://www.youtube.com/embed/z-4s_6Q530I",
  },
  {
    id: 27,
    imgsrc: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2050650/header.jpg?t=1736385712",
    heading: "Resident Evil 4",
    description: "A action-adventure horror game with a rich storyline and a deep character development.",
    details: "Resident Evil 4 offers a unique combination of action, stealth, and horror elements, with a deep storyline and a rich character development.",
    releaseDate: "2010-06-16",
    developer: "Capcom",
    publisher: "Capcom",
    genres: ["All","Action", "Adventure", "Casual"],
    systemRequirements: "PC: Intel i5, 4GB RAM, GTX 650 or equivalent",
    platforms: ["PC", "PS3", "PS4", "Xbox 360", "Xbox One"],
    youtubeGameplay: "https://www.youtube.com/embed/9r9s263v80I",
  },
  {
    id: 28,
    imgsrc: "https://cdn2.unrealengine.com/social-image-chapter4-s3-3840x2160-d35912cc25ad.jpg",
    heading: "Fortnite",
    description: "A battle royale game with a unique combination of action, strategy, and teamwork.",
    details: "Fortnite offers a unique combination of action, strategy, and teamwork, with a deep storyline and a rich character development.",
    releaseDate: "2017-07-25",
    developer: "Epic Games",
    publisher: "Epic Games",
    genres: ["All","Action", "Adventure",],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 1060 or equivalent",
    platforms: ["PC", "PS4", "Xbox One", "Switch"],
    youtubeGameplay: "https://www.youtube.com/embed/omI392UQWkw",
  },
  {
    id: 29,
    imgsrc: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/413150/capsule_616x353.jpg?t=1711128146",
    heading: "Stardew Valley",
    description: "A farming and life simulation game with a rich storyline and a deep character development.",
    details: "Stardew Valley offers a unique combination of farming, life simulation, and social interaction, with a deep storyline and a rich character development.",
    releaseDate: "2016-02-26",
    developer: "ConcernedApe",
    publisher: "ConcernedApe",
    genres: ["All","Family", "Simulation"],
    systemRequirements: "PC: Intel i5, 4GB RAM, GTX 650 or equivalent",
    platforms: ["PC", "Switch"],
    youtubeGameplay: "https://www.youtube.com/embed/kFOHszorXrw",
  },
  {
    id: 30,
    imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg?t=1711128146",
    heading: "The Witcher 3: Wild Hunt",
    description: "An open-world action RPG with a rich narrative and immersive gameplay.",
    details: "The Witcher 3: Wild Hunt is an award-winning open-world RPG set in a fantasy universe. You play as Geralt of Rivia, a monster hunter tasked with finding a child of prophecy in a vast world full of dangerous creatures and complex characters. The game features a deep storyline, meaningful choices, and stunning visuals. With over 100 hours of gameplay, it offers a blend of action, exploration, and storytelling that has captivated millions of players worldwide.",
    releaseDate: "2015-05-19",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genres: ["Action", "Adventure", "RPG"],
    systemRequirements: "PC: Intel i5-2500K, 6GB RAM, GTX 660 or equivalent",
    platforms: ["PC", "PS4", "Xbox One", "Switch"],
    youtubeGameplay: "https://www.youtube.com/embed/c0i88t0Kacs",
  },
  {
    id: 31,
    imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/814380/header.jpg?t=1711128146",
    heading: "Sekiro: Shadows Die Twice",
    description: "A challenging action-adventure game set in feudal Japan.",
    details: "Sekiro: Shadows Die Twice is an action-adventure game developed by FromSoftware. Set in a reimagined feudal Japan, you play as a shinobi warrior on a quest to rescue your kidnapped lord and exact revenge on your enemies. The game is known for its intense combat, precise mechanics, and challenging difficulty. With a focus on stealth, exploration, and swordplay, Sekiro offers a unique experience that tests both skill and strategy.",
    releaseDate: "2019-03-22",
    developer: "FromSoftware",
    publisher: "Activision",
    genres: ["Action", "Adventure"],
    systemRequirements: "PC: Intel i3-2100, 4GB RAM, GTX 760 or equivalent",
    platforms: ["PC", "PS4", "Xbox One"],
    youtubeGameplay: "https://www.youtube.com/embed/rXMX4YJ7Lks",
  },
  {
    id: 32,
    imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg?t=1711128146",
    heading: "Elden Ring",
    description: "An open-world action RPG with a dark fantasy setting.",
    details: "Elden Ring is a collaboration between FromSoftware and George R.R. Martin, offering a vast open-world experience with a dark fantasy theme. Players explore the Lands Between, a world filled with mythical creatures, challenging bosses, and deep lore. The game combines the signature difficulty of FromSoftware's titles with a more accessible open-world structure, allowing for exploration and customization. With its rich storytelling and immersive gameplay, Elden Ring has become a landmark title in the action RPG genre.",
    releaseDate: "2022-02-25",
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    genres: ["Action", "Adventure", "RPG"],
    systemRequirements: "PC: Intel i5-8400, 12GB RAM, GTX 1060 or equivalent",
    platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S"],
    youtubeGameplay: "https://www.youtube.com/embed/E3Huy2cdih0",
  },
  {
    id: 33,
    imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg?t=1711128146",
    heading: "Red Dead Redemption 2",
    description: "An epic open-world adventure set in the Wild West.",
    details: "Red Dead Redemption 2 is an open-world action-adventure game set in the late 1800s. You play as Arthur Morgan, an outlaw and member of the Van der Linde gang, navigating a world of lawlessness and survival. The game features a massive open world, a compelling story, and realistic gameplay mechanics. With its stunning visuals, deep character development, and immersive world, Red Dead Redemption 2 is widely regarded as one of the greatest games of all time.",
    releaseDate: "2018-10-26",
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    genres: ["Action", "Adventure"],
    systemRequirements: "PC: Intel i7-4770K, 12GB RAM, GTX 1060 or equivalent",
    platforms: ["PC", "PS4", "Xbox One"],
    youtubeGameplay: "https://www.youtube.com/embed/gmA6MrX81z4",
  },
  {
    id: 34,
    imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg?t=1711128146",
    heading: "Cyberpunk 2077",
    description: "A futuristic open-world RPG set in Night City.",
    details: "Cyberpunk 2077 is an open-world RPG set in the dystopian future of Night City. You play as V, a mercenary navigating a world of cybernetic enhancements, corporate greed, and crime. The game offers a deep narrative, customizable characters, and a vast open world to explore. Despite its rocky launch, Cyberpunk 2077 has been significantly improved with updates and expansions, offering a rich and immersive experience for fans of the genre.",
    releaseDate: "2020-12-10",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genres: ["Action", "Adventure", "RPG"],
    systemRequirements: "PC: Intel i7-4790, 12GB RAM, GTX 1060 or equivalent",
    platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S"],
    youtubeGameplay: "https://www.youtube.com/embed/LembwKDo1Dk",
  },
  {
    id: 35,
    imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/1240440/header.jpg?t=1711128146",
    heading: "Hogwarts Legacy",
    description: "An open-world action RPG set in the Harry Potter universe.",
    details: "Hogwarts Legacy is an open-world action RPG set in the magical world of Harry Potter. Set in the 1800s, you play as a student at Hogwarts School of Witchcraft and Wizardry, exploring the castle, learning spells, and uncovering a hidden ancient secret. The game offers a rich narrative, detailed world-building, and immersive gameplay. With its stunning visuals and faithful representation of the Harry Potter universe, Hogwarts Legacy has become a must-play for fans of the series.",
    releaseDate: "2023-02-10",
    developer: "Avalanche Software",
    publisher: "Warner Bros. Interactive Entertainment",
    genres: ["Action", "Adventure", "RPG"],
    systemRequirements: "PC: Intel i5-8400, 8GB RAM, GTX 1080 or equivalent",
    platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S"],
    youtubeGameplay: "https://www.youtube.com/embed/1O6Qstncpnc",
  },
    {
      id: 36,
      imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/230410/header.jpg?t=1711128146",
      heading: "Risk of Rain",
      description: "A challenging roguelike action game with a focus on exploration and survival.",
      details: "Risk of Rain is a roguelike action game where players must survive on an alien planet filled with hostile creatures. The game features procedurally generated levels, a variety of playable characters, and a unique difficulty system that increases over time. With its fast-paced combat, cooperative multiplayer mode, and retro pixel art style, Risk of Rain offers a challenging and rewarding experience for fans of the genre.",
      releaseDate: "2013-11-08",
      developer: "Hopoo Games",
      publisher: "Hopoo Games",
      genres: ["Action", "Adventure", "Roguelike"],
      systemRequirements: "PC: Intel Core 2 Duo, 2GB RAM, DirectX 9.0c compatible GPU",
      platforms: ["PC", "Linux", "Mac"],
      youtubeGameplay: "https://www.youtube.com/embed/5VZBn4wQ0q4",
    },
    {
      id: 37,
      imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/237930/header.jpg?t=1711128146",
      heading: "Darkwood",
      description: "A top-down survival horror game with a unique atmosphere and gameplay.",
      details: "Darkwood is a top-down survival horror game that emphasizes atmosphere, exploration, and resource management. Set in a mysterious forest, players must scavenge for supplies, craft tools, and fend off terrifying creatures while uncovering the secrets of the woods. The game features a day-night cycle, permadeath, and a unique narrative structure that adapts to player choices. With its eerie visuals and tense gameplay, Darkwood is a hidden gem for horror enthusiasts.",
      releaseDate: "2017-08-18",
      developer: "Acid Wizard Studio",
      publisher: "Acid Wizard Studio",
      genres: ["Action", "Adventure", "Horror"],
      systemRequirements: "PC: Intel Core 2 Duo, 4GB RAM, GTX 260 or equivalent",
      platforms: ["PC", "PS4", "Switch"],
      youtubeGameplay: "https://www.youtube.com/embed/1O6Qstncpnc",
    },
    {
      id: 38,
      imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/250900/header.jpg?t=1711128146",
      heading: "The Banner Saga",
      description: "A tactical RPG with a rich narrative and hand-drawn visuals.",
      details: "The Banner Saga is a tactical RPG that combines turn-based combat with a deep narrative and stunning hand-drawn visuals. Set in a Viking-inspired world, players must lead a caravan of survivors through a harsh landscape while making difficult choices that impact the story. The game features a unique combat system, memorable characters, and a branching storyline. With its beautiful art style and emotional storytelling, The Banner Saga is a standout title in the strategy RPG genre.",
      releaseDate: "2014-01-14",
      developer: "Stoic Studio",
      publisher: "Versus Evil",
      genres: ["Strategy", "Adventure", "RPG"],
      systemRequirements: "PC: Intel Core 2 Duo, 2GB RAM, DirectX 9.0c compatible GPU",
      platforms: ["PC", "PS4", "Xbox One", "Switch"],
      youtubeGameplay: "https://www.youtube.com/embed/5VZBn4wQ0q4",
    },
    {
      id: 39,
      imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/261030/header.jpg?t=1711128146",
      heading: "Don't Starve",
      description: "A survival game with a unique art style and challenging gameplay.",
      details: "Don't Starve is a survival game where players must gather resources, craft tools, and fend off dangerous creatures to stay alive in a mysterious wilderness. The game features a distinctive Tim Burton-esque art style, permadeath, and a variety of characters with unique abilities. With its challenging gameplay, procedurally generated worlds, and emphasis on exploration, Don't Starve offers a rewarding experience for survival game fans.",
      releaseDate: "2013-04-23",
      developer: "Klei Entertainment",
      publisher: "Klei Entertainment",
      genres: ["Adventure", "Survival", "Simulation"],
      systemRequirements: "PC: Intel Pentium 4, 512MB RAM, DirectX 9.0c compatible GPU",
      platforms: ["PC", "PS4", "Xbox One", "Switch"],
      youtubeGameplay: "https://www.youtube.com/embed/1O6Qstncpnc",
    },
    {
      id: 40,
      imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/274190/header.jpg?t=1711128146",
      heading: "The Flame in the Flood",
      description: "A survival adventure game set in a post-apocalyptic world.",
      details: "The Flame in the Flood is a survival adventure game where players navigate a flooded, post-apocalyptic world by raft and on foot. The game emphasizes resource management, crafting, and exploration as players travel down a procedurally generated river. With its beautiful art style, atmospheric soundtrack, and challenging gameplay, The Flame in the Flood offers a unique take on the survival genre.",
      releaseDate: "2016-02-24",
      developer: "The Molasses Flood",
      publisher: "The Molasses Flood",
      genres: ["Adventure", "Survival", "Simulation"],
      systemRequirements: "PC: Intel Core 2 Duo, 2GB RAM, DirectX 9.0c compatible GPU",
      platforms: ["PC", "PS4", "Xbox One", "Switch"],
      youtubeGameplay: "https://www.youtube.com/embed/5VZBn4wQ0q4",
    },
    {
      id: 41,
      imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/287700/header.jpg?t=1711128146",
      heading: "Crypt of the NecroDancer",
      description: "A rhythm-based roguelike dungeon crawler with an addictive soundtrack.",
      details: "Crypt of the NecroDancer is a unique roguelike dungeon crawler where players move and attack to the beat of the music. The game features a variety of characters, procedurally generated levels, and an incredible soundtrack by Danny Baranowsky. With its innovative gameplay, challenging difficulty, and catchy tunes, Crypt of the NecroDancer is a must-play for fans of rhythm games and roguelikes.",
      releaseDate: "2015-04-23",
      developer: "Brace Yourself Games",
      publisher: "Brace Yourself Games",
      genres: ["Action", "Adventure", "Roguelike"],
      systemRequirements: "PC: Intel Core 2 Duo, 2GB RAM, DirectX 9.0c compatible GPU",
      platforms: ["PC", "PS4", "Xbox One", "Switch"],
      youtubeGameplay: "https://www.youtube.com/embed/1O6Qstncpnc",
    },
      {
        id: 42,
        imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/480490/header.jpg?t=1711128146",
        heading: "Rocket League",
        description: "A high-octane sports game combining soccer with rocket-powered cars.",
        details: "Rocket League is a unique sports game that blends soccer with rocket-powered cars. Players compete in fast-paced matches, performing aerial acrobatics and strategic plays to score goals. The game features customizable cars, various game modes, and cross-platform multiplayer. With its easy-to-learn but hard-to-master gameplay, Rocket League has become a favorite among casual and competitive gamers alike. Its vibrant visuals and thrilling matches make it a standout title in the sports genre.",
        releaseDate: "2015-07-07",
        developer: "Psyonix",
        publisher: "Psyonix",
        genres: ["Sports", "Action", "Family"],
        systemRequirements: "PC: Intel Core 2 Duo, 2GB RAM, DirectX 9.0c compatible GPU",
        platforms: ["PC", "PS4", "Xbox One", "Switch"],
        youtubeGameplay: "https://www.youtube.com/embed/OmMF9EDbmQQ",
      },
      {
        id: 43,
        imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/730310/header.jpg?t=1711128146",
        heading: "Super Mega Baseball 4",
        description: "A fun and accessible baseball game with a cartoonish art style.",
        details: "Super Mega Baseball 4 is a baseball simulation game that combines realistic gameplay with a lighthearted, cartoonish art style. The game features a variety of teams, customizable players, and multiple game modes, including online multiplayer. With its intuitive controls and deep mechanics, it appeals to both casual players and hardcore baseball fans. The game's humor and vibrant visuals make it a refreshing take on the sports genre.",
        releaseDate: "2023-06-02",
        developer: "Metalhead Software",
        publisher: "Electronic Arts",
        genres: ["Sports", "Family", "Simulation"],
        systemRequirements: "PC: Intel i5-3470, 8GB RAM, GTX 650 or equivalent",
        platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X/S", "Switch"],
        youtubeGameplay: "https://www.youtube.com/embed/5VZBn4wQ0q4",
      },
      {
        id: 44,
        imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/676070/header.jpg?t=1711128146",
        heading: "Outlast 2",
        description: "A first-person survival horror game set in a terrifying rural environment.",
        details: "Outlast 2 is a first-person survival horror game that takes players to the remote Arizona desert, where they must uncover the truth behind a mysterious cult. The game emphasizes stealth and evasion, as players have no weapons to defend themselves. With its intense atmosphere, disturbing visuals, and heart-pounding gameplay, Outlast 2 is a chilling experience that pushes the boundaries of horror gaming. The game's narrative and immersive sound design make it a must-play for horror enthusiasts.",
        releaseDate: "2017-04-25",
        developer: "Red Barrels",
        publisher: "Red Barrels",
        genres: ["Horror", "Action", "Adventure"],
        systemRequirements: "PC: Intel i3-530, 4GB RAM, GTX 660 or equivalent",
        platforms: ["PC", "PS4", "Xbox One", "Switch"],
        youtubeGameplay: "https://www.youtube.com/embed/1O6Qstncpnc",
      },
      {
        id: 45,
        imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/381210/header.jpg?t=1711128146",
        heading: "Dead by Daylight",
        description: "A multiplayer horror game where players become survivors or a killer.",
        details: "Dead by Daylight is an asymmetric multiplayer horror game where four survivors must escape a deadly killer controlled by another player. The game features iconic characters from popular horror franchises, as well as original ones. Survivors must work together to repair generators and escape, while the killer hunts them down. With its tense gameplay, variety of maps, and regular updates, Dead by Daylight has become a staple in the horror multiplayer genre.",
        releaseDate: "2016-06-14",
        developer: "Behaviour Interactive",
        publisher: "Behaviour Interactive",
        genres: ["Horror", "Action", "Multiplayer"],
        systemRequirements: "PC: Intel i3-4170, 8GB RAM, GTX 460 or equivalent",
        platforms: ["PC", "PS4", "Xbox One", "Switch"],
        youtubeGameplay: "https://www.youtube.com/embed/JGhIXLO3ul8",
      },
      {
        id: 46,
        imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/257850/header.jpg?t=1711128146",
        heading: "The Golf Club 2019",
        description: "A realistic golf simulation game with a focus on customization and precision.",
        details: "The Golf Club 2019 is a realistic golf simulation game that offers a true-to-life golfing experience. Players can create and customize their own courses, compete in online tournaments, and play through a career mode. The game features precise controls, realistic physics, and stunning visuals. With its emphasis on authenticity and player creativity, The Golf Club 2019 is a must-play for golf enthusiasts and simulation fans.",
        releaseDate: "2018-08-28",
        developer: "HB Studios",
        publisher: "2K Sports",
        genres: ["Sports", "Simulation"],
        systemRequirements: "PC: Intel i5-760, 8GB RAM, GTX 560 or equivalent",
        platforms: ["PC", "PS4", "Xbox One"],
        youtubeGameplay: "https://www.youtube.com/embed/5VZBn4wQ0q4",
      },
      {
        id: 47,
        imgsrc: "https://cdn.cloudflare.steamstatic.com/steam/apps/739630/header.jpg?t=1711128146",
        heading: "Phasmophobia",
        description: "A cooperative horror game where players investigate haunted locations.",
        details: "Phasmophobia is a cooperative horror game where players take on the role of ghost hunters investigating haunted locations. Using a variety of tools, players must gather evidence to identify the type of ghost haunting the area. The game features realistic sound design, dynamic AI behavior, and VR support, making it an immersive and terrifying experience. With its emphasis on teamwork and suspense, Phasmophobia has become a popular choice for horror fans and streamers alike.",
        releaseDate: "2020-09-18",
        developer: "Kinetic Games",
        publisher: "Kinetic Games",
        genres: ["Horror", "Action", "Multiplayer"],
        systemRequirements: "PC: Intel i5-4590, 8GB RAM, GTX 970 or equivalent",
        platforms: ["PC"],
        youtubeGameplay: "https://www.youtube.com/embed/1O6Qstncpnc",
      },
];


export default gameData;
