const gameData = [
  {
    id: 1,
    imgsrc: "https://www.shutterstock.com/shutterstock/photos/2397428743/display_1500/stock-photo-introducing-the-game-that-has-been-awaited-for-years-grand-theft-auto-vi-2397428743.jpg",
    heading: "Grand Theft Auto VI",
    description: "Introducing the game that has been awaited for years, Grand Theft Auto VI! Click show more for details.",
    details: "Grand Theft Auto VI is an upcoming open-world action-adventure game developed by Rockstar Games. Set in Vice City, it features a gripping storyline, immersive gameplay, and next-gen graphics.Grand Theft Auto VI is the highly anticipated entry in Rockstar Games' iconic franchise. Set in the sprawling, dynamic world of Vice City, the game promises an immersive experience with a rich narrative, detailed environments, and complex characters. Players can explore a vast open world filled with opportunities for crime, adventure, and mayhem. The game's next-gen graphics and enhanced mechanics offer a seamless and realistic gaming experience. With a focus on storytelling, Grand Theft Auto VI delves into the gritty underworld of Vice City, introducing new protagonists and storylines. ",
    releaseDate: "2025-11-17",
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    genres: ["Action", "Adventure", "Open World"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 970 or equivalent",
    platforms: ["PC", "PS5", "Xbox Series X"],
    youtubeGameplay: "https://www.youtube.com/embed/QdBZY2fkU-0?si=UiPhkQcOQ0q_oXWI",
  },
  {
    id: 2,
    imgsrc: "https://assets.nintendo.com/image/upload/ar_16:9,b_auto:border,c_lpad/b_white/f_auto/q_auto/dpr_1.5/c_scale,w_900/ncom/software/switch/70010000047794/40f9e2f6d344d2607d4be72c6c4ebd3c18717ff87a56d6bbc303c42e58dd570d",
    heading: "FIFA 23",
    description: "FIFA 23 is a football simulation game that offers realistic gameplay, enhanced graphics, and new features like HyperMotion2 technology.",
    details: "FIFA 23 introduces women's club football, HyperMotion2 gameplay technology, and cross-play. Enjoy updated rosters, improved animations, and an immersive football experience.FIFA 23, developed by EA Sports, is the latest installment in the long-running football simulation series. The game introduces HyperMotion2 technology, enhancing the realism and fluidity of player movements and animations. FIFA 23 features updated rosters, reflecting the latest transfers and player ratings, along with improved graphics and stadium atmospheres. The game includes women's club football, expanding the diversity of teams and competitions available. With cross-play functionality, players can compete with friends across different platforms. FIFA 23's Career Mode allows players to manage a team, make strategic decisions, and guide their club to glory. ",
    releaseDate: "2022-09-30",
    developer: "EA Sports",
    publisher: "EA Sports",
    genres: ["Sports", "Simulation"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 1050 or equivalent",
    platforms: ["PC", "PS5", "Xbox Series X"],
    youtubeGameplay: "https://www.youtube.com/embed/Ye1Go-Ke1r4?si=2U3-Pgt09yFiLzc8",
  },
  {
    id: 3,
    imgsrc: "https://i.ytimg.com/vi/EAPldVCRo-g/maxresdefault.jpg",
    heading: "The Legend of Zelda: Skyward Sword",
    description: "Join Link on an epic adventure through the skies and beyond in this remastered version of The Legend of Zelda: Skyward Sword.",
    details: "Experience The Legend of Zelda: Skyward Sword HD with enhanced visuals, refined controls, and a rich storyline that delves into the origins of the Master Sword. The Legend of Zelda: Skyward Sword HD is a remastered version of the beloved classic, offering enhanced visuals and refined controls. Set in the fantastical world of Hyrule, the game follows the adventures of Link as he embarks on a quest to rescue Princess Zelda and uncover the origins of the Master Sword. Players can explore a vast sky world, filled with floating islands and dungeons, using the unique motion controls of the Nintendo Switch. The game's story is rich with lore, delving into the mythology of the Zelda series. Combat is intuitive, with players using the Joy-Con controllers to wield the sword and shield.",
    releaseDate: "2023-03-03",
    developer: "Nintendo",
    publisher: "Nintendo",
    genres: ["Action", "Adventure", "RPG"],
    systemRequirements: "Exclusive on Nintendo Switch",
    platforms: ["Nintendo Switch"],
    youtubeGameplay: "https://www.youtube.com/embed/EAPldVCRo-g?si=T_YfrKtjUT0FKjvp",
  },
  {
    id: 4,
    imgsrc: "https://i.ytimg.com/vi/D1H4o4FW-wA/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCeEG47i3U5Bou3VKKhvH0bC4TzjQ",
    heading: "Elden Ring",
    description: "Elden Ring, a collaboration between FromSoftware and George R.R. Martin, takes you on a dark fantasy adventure.",
    details: "Elden Ring features a vast open world, deep lore, and challenging combat. Explore the mysterious Lands Between and forge your own destiny. Elden Ring, developed by FromSoftware in collaboration with George R.R. Martin, is a dark fantasy action RPG set in the vast and mysterious Lands Between. Players take on the role of a Tarnished, a being seeking to reclaim the power of the Elden Ring and become the Elden Lord. The game features a sprawling open world, filled with challenging enemies, intricate dungeons, and hidden secrets. Elden Ring's combat system combines elements of FromSoftware's previous titles, with a focus on precise timing and strategy. Players can customize their character's abilities, weapons, and equipment to suit their playstyle.",
    releaseDate: "2022-02-25",
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    genres: ["Action", "RPG", "Adventure"],
    systemRequirements: "PC: Intel i7, 16GB RAM, GTX 1070 or equivalent",
    platforms: ["PC", "PS5", "Xbox Series X"],
    youtubeGameplay: "https://www.youtube.com/embed/E3Huy2cdih0?si=IRKVeZLuu6-Nr1-g",
  },
  {
    id: 5,
    imgsrc: "https://www.cyberpunk.net/build/images/social-thumbnail-en-ddcf4d23.jpg",
    heading: "Cyberpunk 2077",
    description: "Immerse yourself in the neon-lit streets of Night City in Cyberpunk 2077. Experience a gripping story and dynamic characters.",
    details: "Cyberpunk 2077 is an open-world RPG set in a futuristic metropolis, where choices shape your story in a city full of intrigue and high-tech enhancements. The game's narrative is driven by player choices, with branching storylines and multiple endings. Night City is a vibrant and immersive world, filled with diverse characters, bustling streets, and high-tech gadgets. The game's combat system combines gunplay, melee attacks, and hacking abilities, allowing players to approach challenges in various ways. Cyberpunk 2077 also features a deep customization system, enabling players to modify V's appearance, skills, and augmentations. The game's rich lore and detailed environments create a captivating experience, while its next-gen graphics and dynamic weather effects enhance immersion. ",
    releaseDate: "2020-12-10",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genres: ["RPG", "Open World", "Sci-Fi"],
    systemRequirements: "PC: Intel i7, 16GB RAM, GTX 1080 or equivalent",
    platforms: ["PC", "PS5", "Xbox Series X"],
    youtubeGameplay: "https://www.youtube.com/embed/8X2kIfS6fb8?si=O-bCequMmTvNT0lr",
  },
  {
    id: 6,
    imgsrc: "https://cdn1.epicgames.com/offer/cbd5b3d310a54b12bf3fe8c41994174f/EGS_VALORANT_RiotGames_S1_2560x1440-1dade6e50659c8e05805cb150b349e56",
    heading: "Valorant",
    description: "Valorant is a competitive tactical shooter from Riot Games, blending precise gunplay with unique agent abilities.",
    details: "Valorant is a team-based shooter where strategy and skill combine. Choose an agent, master your abilities, and compete in fast-paced tactical battles. Each agent in Valorant has distinct abilities that can be used to gain an advantage in combat, from deploying barriers to healing teammates. The game's mechanics are designed to reward skill and precision, with a focus on headshots and recoil control. Valorant's maps are carefully crafted to offer various strategic opportunities, including tight corridors, open spaces, and verticality. The game's ranked mode provides a competitive environment for players to test their skills and climb the leaderboards. Valorant also features a vibrant esports scene, with regular tournaments and events. Riot Games continues to support Valorant with frequent updates, introducing new agents, maps, and gameplay changes to keep the experience fresh and engaging.",
    releaseDate: "2020-06-02",
    developer: "Riot Games",
    publisher: "Riot Games",
    genres: ["FPS", "Tactical", "Competitive"],
    systemRequirements: "PC: Intel i3, 4GB RAM, integrated graphics",
    platforms: ["PC"],
    youtubeGameplay: "https://www.youtube.com/embed/e_E9W2vsRbQ?si=ksd-hMlosWWHcU9S",
  },
  {
    id: 7,
    imgsrc: "https://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2015/5/13/1431520130189/8bfad8ae-5a24-4617-988e-ccafee83324f-1020x612.jpeg?width=700&quality=85&auto=format&fit=max&s=8a7d3e78ea1329d9442f2b175bc7eb14",
    heading: "The Witcher 3: Wild Hunt",
    description: "An epic RPG with a rich story and immersive world.",
    details: "The Witcher 3: Wild Hunt is an action RPG set in a fantasy world. Players take on the role of Geralt of Rivia, a monster hunter searching for his adopted daughter. The game features a vast open world, engaging combat, and deep storytelling. The open world of The Witcher 3 is filled with diverse regions, from bustling cities to dense forests, each with its own unique quests and challenges. Combat is dynamic and requires strategic use of Geralt's abilities, including swordplay, magic, and alchemy. The game's deep lore and detailed environments create a captivating experience, while its stunning visuals and atmospheric soundtrack enhance immersion. The Witcher 3 also features two major expansions, Hearts of Stone and Blood and Wine, which introduce new storylines, characters, and regions to explore. ",
    releaseDate: "2015-05-19",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genres: ["RPG", "Open World", "Fantasy"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 770 or equivalent",
    platforms: ["PC", "PS4", "Xbox One", "Nintendo Switch"],
    youtubeGameplay: "https://www.youtube.com/embed/c0i88t0Kacs?si=1Z_8bxMHWbN-HJPJ",
  },
  {
    id: 8,
    imgsrc: "https://store-images.s-microsoft.com/image/apps.60323.13950084616086229.56d90257-df96-4000-bf85-a64704b3b019.d4ae0460-e24a-41ce-9e09-a92dc478362f?mode=scale&q=90&h=720&w=1280&format=jpg",
    heading: "Minecraft",
    description: "A sandbox game where you can build and explore endlessly.",
    details: "Minecraft is a sandbox game that allows players to explore, build, and create in a blocky, procedurally-generated world. Players can gather resources, craft items, and build structures while facing challenges such as monsters and environmental hazards. The game features various modes, including Survival, Creative, and Adventure, each offering a different experience. In Survival mode, players must gather resources, craft items, and fend off hostile creatures to survive. Creative mode allows players to build freely without constraints, with unlimited resources at their disposal. Adventure mode offers custom maps and challenges created by the community. Minecraft's blocky art style and simple mechanics make it accessible to players of all ages. The game also supports multiplayer, allowing players to collaborate or compete with others online. Minecraft's vibrant community continues to create new content, from mods and texture packs to custom maps and mini-games. ",
    releaseDate: "2011-11-18",
    developer: "Mojang Studios",
    publisher: "Mojang Studios",
    genres: ["Sandbox", "Survival", "Adventure"],
    systemRequirements: "PC: Intel i3, 4GB RAM, integrated graphics",
    platforms: ["PC", "PS4", "Xbox One", "Nintendo Switch", "Mobile"],
    youtubeGameplay: "https://www.youtube.com/embed/MmB9b5njVbA?si=SBTFEs3Oh6repGl2",
  },
  {
    id: 9,
    imgsrc: "https://gaming-cdn.com/images/products/9456/616x353/league-of-legends-pc-game-cover.jpg?v=1662363312",
    heading: "League of Legends",
    description: "A highly competitive multiplayer online battle arena game.",
    details: "League of Legends is a MOBA game where players control a champion with unique abilities and work with their team to destroy the enemy's Nexus. The game requires strategy, teamwork, and quick reflexes.Each match begins with players choosing their champions and selecting items to enhance their abilities. The game's map, Summoner's Rift, features three lanes, a jungle area, and various objectives, such as turrets and inhibitors, that players must control to gain an advantage. League of Legends has a diverse roster of champions, each with their own playstyle and lore. The game's ranked mode provides a competitive environment where players can test their skills and climb the ladder. Riot Games regularly updates the game with balance changes, new champions, and events, keeping the experience fresh and engaging. ",
    releaseDate: "2009-10-27",
    developer: "Riot Games",
    publisher: "Riot Games",
    genres: ["MOBA", "Strategy", "Competitive"],
    systemRequirements: "PC: Intel i3, 4GB RAM, integrated graphics",
    platforms: ["PC"],
    youtubeGameplay: "https://www.youtube.com/embed/vzHrjOMfHPY?si=CDwzvTaELKTh_YKW",
  },
  {
    id: 10,
    imgsrc: "https://miro.medium.com/v2/resize:fit:800/0*tEg_A9lgZRP4_LkI.jpg",
    heading: "Counter-Strike: Global Offensive",
    description: "A classic first-person shooter with intense gameplay.",
    details: "Counter-Strike: Global Offensive (CS: GO) is a first-person shooter where players join either the terrorist or counter-terrorist team. The game features various modes, including competitive matchmaking, where strategy and precision are key. The game's mechanics reward precise aiming, map knowledge, and teamwork. Each round begins with players purchasing weapons and equipment using money earned from previous rounds. CS: GO's maps are meticulously designed to offer various strategic opportunities, from tight corridors to open spaces. The game's competitive matchmaking provides a ranked environment where players can test their skills and climb the ladder. CS: GO also features a vibrant community and esports scene, with regular tournaments and events. Valve continues to support the game with updates, introducing new maps, weapons, and gameplay changes. The game's legacy and enduring popularity make it a staple in the first-person shooter genre.",
    releaseDate: "2012-08-21",
    developer: "Valve",
    publisher: "Valve",
    genres: ["FPS", "Action", "Shooter"],
    systemRequirements: "PC: Intel i3, 4GB RAM, GTX 750 or equivalent",
    platforms: ["PC"],
    youtubeGameplay: "https://www.youtube.com/embed/edYCtaNueQY?si=Lxxbk7D7tRVaef4w",
  },
  {
    id: 11,
    imgsrc: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/570/header.jpg?t=1739210483",
    heading: "Dota 2",
    description: "A popular multiplayer online battle arena (MOBA) game with deep strategy.",
    details: "Dota 2 is a competitive MOBA developed by Valve, featuring a vast roster of heroes, strategic gameplay, and intense team battles. Players pick a hero and work with their team to destroy the enemy's Ancient while defending their own. The game has a steep learning curve but offers immense rewards for skillful play. With regular updates, an active esports scene, and millions of players worldwide, Dota 2 remains one of the most competitive online games. The game's competitive scene is thriving, with major tournaments like The International drawing massive audiences and offering substantial prize pools. With regular updates, a dedicated community, and a rich esports ecosystem, Dota 2 continues to be a cornerstone of the MOBA genre.",
    releaseDate: "2013-07-09",
    developer: "Valve",
    publisher: "Valve",
    genres: ["MOBA", "Strategy", "Esports"],
    systemRequirements: "PC: Intel i3, 4GB RAM, DirectX 9 compatible GPU",
    platforms: ["PC"],
    youtubeGameplay: "https://www.youtube.com/embed/-cSFPIwMEq4?si=8XtQt4JW-Ho7EYJc",
  },
  {
    id: 12,
    imgsrc: "https://i.pinimg.com/736x/b0/cd/bd/b0cdbda5558cce6196f046b11f945c3b.jpg",
    heading: "PUBG: Battlegrounds",
    description: "A battle royale game where players fight to be the last one standing.",
    details: "PUBG (PlayerUnknown's Battlegrounds) is a battle royale shooter where 100 players parachute onto an island and fight to survive. Players scavenge for weapons, armor, and supplies while staying within a shrinking safe zone. The game emphasizes tactical play, gunfights, and survival instincts. PUBG has been a pioneer in the battle royale genre, inspiring countless other games and maintaining a dedicated player base. With a variety of maps, game modes, and frequent updates, PUBG continues to captivate millions of players worldwide and has significantly influenced the popularity of the battle royale genre.",
    releaseDate: "2017-12-20",
    developer: "PUBG Studios",
    publisher: "Krafton",
    genres: ["Battle Royale", "Shooter", "Survival"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 960 or equivalent",
    platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X", "Mobile"],
    youtubeGameplay: "https://www.youtube.com/embed/u1oqfdh4xBY?si=0yPLoFKXXQjbU1si",
  },
  {
    id: 13,
    imgsrc: "https://assets.xboxservices.com/assets/a0/02/a0029671-98a2-4955-a9e7-ef32cd0eb544.jpg?n=CoD-MW-II_GLP-Page-Hero-Poster-1084_1920x1080.jpg",
    heading: "Call of Duty: Modern Warfare II",
    description: "A first-person shooter with realistic combat and engaging multiplayer.",
    details: "Call of Duty: Modern Warfare II is a high-paced first-person shooter that blends an intense campaign with competitive multiplayer modes. The game features realistic gunplay, cinematic storytelling, and a variety of maps and weapons. With Warzone integration, it also includes battle royale and co-op missions, making it one of the most popular FPS games.The game features a variety of modes, including a thrilling campaign where players engage in high-stakes missions, a competitive multiplayer mode with new and classic game types, and a cooperative Special Ops mode that requires tactical teamwork. ",
    releaseDate: "2022-10-28",
    developer: "Infinity Ward",
    publisher: "Activision",
    genres: ["FPS", "Action", "Shooter"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 970 or equivalent",
    platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X"],
    youtubeGameplay: "https://www.youtube.com/embed/ztjfwecrY8E?si=ThM_k8anY973-kNG",
  },
  {
    id: 14,
    imgsrc: "https://media.contentapi.ea.com/content/dam/need-for-speed/nfs-heat/common/wallpapers/nsfh-wallpaper-keyart-deluxe-16x9.png",
    heading: "Need for Speed: Heat",
    description: "A high-speed racing game with a thrilling open-world experience.",
    details: "Need for Speed: Heat is an open-world racing game that offers intense street races, police chases, and car customization. Players can race in sanctioned daytime events or take risks in illegal nighttime street races to earn rewards. The game features stunning graphics, a diverse selection of cars, and immersive driving mechanics, making it a favorite among racing enthusiasts. With a diverse roster of cars, extensive customization options, and a gripping storyline, NFS Heat captures the adrenaline-pumping essence of street racing and the allure of the underground racing scene. The game's stunning visuals, dynamic weather, and engaging gameplay make it a standout title in the Need for Speed series.",
    releaseDate: "2019-11-08",
    developer: "Ghost Games",
    publisher: "Electronic Arts",
    genres: ["Racing", "Action", "Open World"],
    systemRequirements: "PC: Intel i5, 8GB RAM, GTX 760 or equivalent",
    platforms: ["PC", "PS4", "Xbox One"],
    youtubeGameplay: "https://www.youtube.com/embed/9ewiJJe_nYI?si=Nj7Nv8VkcoZgD3cZ",
  },
  
];

export default gameData;
